plugins {
    id 'java'
    id 'journey.java-conventions'
    id 'journey-paper-plugin-conventions' apply false
}

version = '1.2.0'

configure(journeyPaperPlugin) {
    pluginName = 'JourneyEssentials'
}

apply plugin: 'journey-paper-plugin-conventions'

repositories {
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://repo.essentialsx.net/releases/' }
}

dependencies {
    implementation project(':api')
    implementation project(':paper-api')
    implementation('net.essentialsx:EssentialsX:2.20.1') {
        exclude group: "org.spigotmc", module: "spigot-api"
    }
    implementation('net.essentialsx:EssentialsXSpawn:2.20.1') {
        exclude group: "org.spigotmc", module: "spigot-api"
    }
}
